### ISSUE TITLE
wget install.sh over entire repository

### ISSUE THREAD

**Issue by ElijahPepe** [murar8/firefox-deflector#1]
Quick suggestion: You could alter install.sh to make the installation command smaller; instead of downloading the entire repository, install.sh wgets firefox-deflector.sh/.desktop.

**Comment by murar8** [comment]
Hey that's a pretty cool idea, but at least on the initial stages I would like to stay with symlinks so if users decide to clone the repo to iron out a bug they can do so very easily. Also a couple more text files is not a whole lot of storage overhead.
