### ISSUE TITLE
Windows Version?

### ISSUE THREAD

**Issue by DanitiKain** [murar8/firefox-deflector#3]
I know you work in linux and found this post on reditt. Is there anyway fo your to convert this to windows as well or have some friends that might be able to do so?

**Comment by murar8** [comment]
I believe it is doable but registering it as a browser is a little bit trickier. As soon as I have some free time I will look into it.

**Comment by DanitiKain** [comment]
This would be huge win for me. Thank you!

**Comment by DanitiKain** [comment]
Any updates on this for windows?

**Comment by murar8** [comment]
Sorry man but lately I have been really busy and I don't think I will be able work on this.
