### ISSUE TITLE
Marked 'Linux Only' yet is specific to PopOS

### ISSUE THREAD

**Issue by ben2talk** [murar8/firefox-deflector#4]
It's annoying when 'Ubuntu' or 'Pop' users think they are using generic Linux.

This script doesn't work with Arch, or with Plasma, for example.

**Comment by murar8** [comment]
I provide this script free of charge to users that I developed in my free time. You will notice on the bottom of the readme I am using a very permissive license that allows you to take the script, fix it yourself, and publish your own fork for people to use. If instead you would like to help me debugging and improve the product I will need to see the output of `ps -F -u $UID`.
